### ISSUE TITLE
Exception while calling to AuthorizationManager.getInstance().getUserIdentity().getDisplayName()

### ISSUE THREAD

**Issue by cirilla** [ibm-bluemix-mobile-services/bms-clientsdk-android-core#11]
If I'm calling to AuthorizationManager.getInstance().getUserIdentity().getDisplayName() before logging in, I'm getting an exception. I expect it to return me an empty string

Process: com.ibm.mobilefirst.mobileedge.gym, PID: 4627
                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ibm.mobilefirst.mobileedge.gym/com.ibm.mobilefirst.mobileedge.gym.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
                                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
                                                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                                      at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
                                                                                      at org.json.JSONTokener.nextValue(JSONTokener.java:94)
                                                                                      at org.json.JSONObject.<init>(JSONObject.java:156)
                                                                                      at org.json.JSONObject.<init>(JSONObject.java:173)
                                                                                      at com.ibm.mobilefirstplatform.clientsdk.android.security.internal.preferences.SharedPreferencesManager$JSONPreference.getAsMap(SharedPreferencesManager.java:104)
                                                                                      at com.ibm.mobilefirstplatform.clientsdk.android.security.api.AuthorizationManager.getUserIdentity(AuthorizationManager.java:178)
                                                                                      at com.ibm.mobilefirst.mobileedge.gym.MainActivity.onCreate(MainActivity.java:35)
                                                                                      at android.app.Activity.performCreate(Activity.java:5933)
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
                                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:135) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5221) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by AnthonyOliveri** [comment]
Closing this issue since it is stale and no longer applies.
